---
title: "lab_report_knapsack"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lab_report_knapsack}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Answers to questions
## 1.1.2
### How much time does it takes to run the algorithm for n = 16 objects?
After running: `brute_force_knapsack(x = knapsack_objects[1:16,], W = 3500)`

Output:
```
> summaryRprof(tmp, lines = "show", memory = "both")$sampling.time
[1] 0.58
```
## 1.1.3
### How much time does it takes to run the algorithm for n = 500 objects?
After running: `knapsack_dynamic(x = knapsack_objects[1:500,], W = 3500)`

Output:
```
> summaryRprof(tmp, lines = "show", memory = "both")$sampling.time
[1] 155.52
```
## 1.1.4
### How much time does it takes to run the algorithm for n = 1000000 objects?
After running: 
```
> set.seed(42)
> n <- 1000000
> knapsack_objects <-
+     data.frame(
+         w=sample(1:4000, size = n, replace = TRUE),
+         v=runif(n = n, 0, 10000)
+     )
> greedy_knapsack(x = knapsack_objects, W = 3500)
```

Output:
```
> summaryRprof(tmp, lines = "show", memory = "both")$sampling.time
[1] 1.56
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Knapsack)
```
